# Use Node.js as the base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy frontend source code
COPY src/ ./src
COPY package*.json ./

# Install dependencies and build
RUN npm install && npm run build

# Expose the frontend port
EXPOSE 8080

# Start the frontend application
CMD ["npm", "start"]
