# Use Node.js as the base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy users-api source code
COPY . .

# Install dependencies and build
RUN npm install && npm run build

# Expose the required port
EXPOSE 8083

# Start the users-api application
CMD ["npm", "start"]
