# Use Python as the base image
FROM python:3.11-alpine

# Set working directory
WORKDIR /app

# Copy the application code and dependencies
COPY main.py .
COPY requirement.txt .

# Install required Python packages
RUN pip install --no-cache-dir -r requirement.txt

# Expose the required port if necessary (optional)
# EXPOSE 8084

# Start the log message processor
CMD ["python", "main.py"]
