# Use Python as the base image
FROM python:3.8-alpine

# Set working directory
WORKDIR /app

# Install build dependencies
RUN apk add --no-cache gcc musl-dev

# Copy the application code and dependencies
COPY main.py .
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the required port (optional)
# EXPOSE 8084

# Start the log message processor
CMD ["python", "main.py"]